-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity BinToBcd is
port (
    switch_input : IN STD_LOGIC_VECTOR (7 downto 0);
    bcd_output_digit_1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    bcd_output_digit_2 : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of BinToBcd is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "BinToBcd_BinToBcd,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.876000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=77,HLS_VERSION=2022_2}";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_19A : STD_LOGIC_VECTOR (16 downto 0) := "00000000110011010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal mul_ln1513_fu_76_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1513_fu_76_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1513_fu_76_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_97_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_113_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln_fu_105_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln186_1_fu_123_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln186_fu_131_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln186_fu_93_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln1513_fu_76_p00 : STD_LOGIC_VECTOR (16 downto 0);

    component BinToBcd_mul_8ns_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;



begin
    mul_8ns_10ns_17_1_1_U1 : component BinToBcd_mul_8ns_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => mul_ln1513_fu_76_p0,
        din1 => mul_ln1513_fu_76_p1,
        dout => mul_ln1513_fu_76_p2);




    bcd_output_digit_1 <= mul_ln1513_fu_76_p2(15 downto 12);
    bcd_output_digit_2 <= std_logic_vector(unsigned(sub_ln186_fu_131_p2) + unsigned(trunc_ln186_fu_93_p1));
    mul_ln1513_fu_76_p0 <= mul_ln1513_fu_76_p00(8 - 1 downto 0);
    mul_ln1513_fu_76_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(switch_input),17));
    mul_ln1513_fu_76_p1 <= ap_const_lv17_19A(10 - 1 downto 0);
    shl_ln186_1_fu_123_p3 <= (tmp_1_fu_113_p4 & ap_const_lv1_0);
    shl_ln_fu_105_p3 <= (tmp_fu_97_p3 & ap_const_lv3_0);
    sub_ln186_fu_131_p2 <= std_logic_vector(unsigned(shl_ln_fu_105_p3) - unsigned(shl_ln186_1_fu_123_p3));
    tmp_1_fu_113_p4 <= mul_ln1513_fu_76_p2(14 downto 12);
    tmp_fu_97_p3 <= mul_ln1513_fu_76_p2(12 downto 12);
    trunc_ln186_fu_93_p1 <= switch_input(4 - 1 downto 0);
end behav;
