// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="BinToBcd_BinToBcd,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.876000,HLS_SYN_LAT=0,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=77,HLS_VERSION=2022_2}" *)

module BinToBcd (
        switch_input,
        bcd_output_digit_1,
        bcd_output_digit_2
);


input  [7:0] switch_input;
output  [3:0] bcd_output_digit_1;
output  [3:0] bcd_output_digit_2;

wire   [7:0] mul_ln1513_fu_76_p0;
wire   [9:0] mul_ln1513_fu_76_p1;
wire   [16:0] mul_ln1513_fu_76_p2;
wire   [0:0] tmp_fu_97_p3;
wire   [2:0] tmp_1_fu_113_p4;
wire   [3:0] shl_ln_fu_105_p3;
wire   [3:0] shl_ln186_1_fu_123_p3;
wire   [3:0] sub_ln186_fu_131_p2;
wire   [3:0] trunc_ln186_fu_93_p1;
wire   [16:0] mul_ln1513_fu_76_p00;

BinToBcd_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U1(
    .din0(mul_ln1513_fu_76_p0),
    .din1(mul_ln1513_fu_76_p1),
    .dout(mul_ln1513_fu_76_p2)
);

assign mul_ln1513_fu_76_p00 = switch_input;

assign shl_ln186_1_fu_123_p3 = {{tmp_1_fu_113_p4}, {1'd0}};

assign shl_ln_fu_105_p3 = {{tmp_fu_97_p3}, {3'd0}};

assign sub_ln186_fu_131_p2 = (shl_ln_fu_105_p3 - shl_ln186_1_fu_123_p3);

assign tmp_1_fu_113_p4 = {{mul_ln1513_fu_76_p2[14:12]}};

assign tmp_fu_97_p3 = mul_ln1513_fu_76_p2[32'd12];

assign trunc_ln186_fu_93_p1 = switch_input[3:0];

assign bcd_output_digit_1 = {{mul_ln1513_fu_76_p2[15:12]}};

assign bcd_output_digit_2 = (sub_ln186_fu_131_p2 + trunc_ln186_fu_93_p1);

assign mul_ln1513_fu_76_p0 = mul_ln1513_fu_76_p00;

assign mul_ln1513_fu_76_p1 = 17'd410;

endmodule //BinToBcd
